In [2]:
# Import libraries
"""
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns
from patsy import dmatrix
import datetime
"""

# Pretty display for notebooks
%matplotlib inline

# Ignore the warnings
import warnings
warnings.filterwarnings('ignore')

# Load the dataset
weather = pd.read_csv("../asset/weather.csv")

# Success - Display the first record
print("weather  data : ", weather.shape)

import awesome_functions as cf

# 원본을 유지하기 위해서 카피
df_weather = weather.copy()

# heatmap을 위한 cmap은 이거 계속 쓰시면 됩니다.
cmap = sns.light_palette("orange", as_cmap=True)

from statsmodels.stats.outliers_influence import variance_inflation_factor

weather  data :  (20517, 20)

In [13]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
def getVif(df):
    vif = pd.DataFrame()
    vif["VIF Factor"] = [variance_inflation_factor(df.values, i) for i in range(df.shape[1])]
    vif["features"] = df.columns
    vif = vif.sort_values("VIF Factor").reset_index(drop=True)
    return vif

In [24]:
station_1 = cf.getSpecifiedWeatherData(df_weather, 1)
temp = cf.isThereNoneData(station_1)

M Data over 60% : ['depart', 'snowfall']
T Data over 60% : []
B Data over 60% : ['sunrise', 'sunset']

In [25]:
cf.remove_columns(station_1, ["date", "codesum", "station_nbr", 'depart', 'snowfall', 'sunrise', 'sunset'])
station_1_dropped_all = cf.remove_m_row(station_1)
getVif(station_1_dropped_all)

제거한 컬럼명 : ['date', 'codesum', 'station_nbr', 'depart', 'snowfall', 'sunrise', 'sunset']
원본 데이터프레임 length : 1035
제거하고 싶은 컬럼 : ['tmax', 'tmin', 'tavg', 'dewpoint', 'wetbulb', 'heat', 'cool', 'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed']
제거한 int 컬럼 : ['tmax', 'tmin', 'tavg', 'dewpoint', 'wetbulb', 'heat', 'cool']
제거한 float 컬럼 : ['preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed']
제거한 후 데이터프레임 length : 1012

      VIF Factor     features
0       1.447042  preciptotal
1       1.528504    resultdir
2      14.907789  resultspeed
3      16.415881     avgspeed
4      92.648621     dewpoint
5     101.226962     sealevel
6     102.757359  stnpressure
7     176.840528         cool
8     332.320483      wetbulb
9    1248.429987         tmin
10   1529.098433         tmax
11   3179.803938         heat
12  71418.719163         tavg

In [19]:
station_2 = cf.getSpecifiedWeatherData(df_weather, 2)
temp = cf.isThereNoneData(station_2)

M Data over 60% : []
T Data over 60% : []
B Data over 60% : []

In [18]:
cf.remove_columns(station_2, ["date", "codesum", "station_nbr"])
station_2_dropped_all = cf.remove_m_row(station_2)
getVif(station_2_dropped_all)

제거한 컬럼명 : ['date', 'codesum', 'station_nbr']
원본 데이터프레임 length : 1035
제거하고 싶은 컬럼 : ['tmax', 'tmin', 'tavg', 'depart', 'dewpoint', 'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'snowfall', 'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed']
제거한 int 컬럼 : ['tmax', 'tmin', 'tavg', 'dewpoint', 'wetbulb', 'heat', 'cool', 'sunrise', 'sunset']
제거한 float 컬럼 : ['depart', 'snowfall', 'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed']
제거한 후 데이터프레임 length : 968

      VIF Factor     features
0       1.313102     snowfall
1       1.516388    resultdir
2       1.523594  preciptotal
3       2.548285       depart
4      10.979643  resultspeed
5      12.174054     avgspeed
6      14.348918       sunset
7      24.543842      sunrise
8     105.430011     dewpoint
9     121.395238  stnpressure
10    121.895450     sealevel
11    143.800609         cool
12    388.601222      wetbulb
13   1177.441986         tmin
14   1393.158872         tmax
15   4651.250670         heat
16  70944.725252         tavg

In [20]:
station_3 = cf.getSpecifiedWeatherData(df_weather, 3)
temp = cf.isThereNoneData(station_3)

M Data over 60% : []
T Data over 60% : []
B Data over 60% : []

In [21]:
cf.remove_columns(station_3, ["date", "codesum", "station_nbr"])
station_3_dropped_all = cf.remove_m_row(station_3)
getVif(station_3_dropped_all)

제거한 컬럼명 : ['date', 'codesum', 'station_nbr']
원본 데이터프레임 length : 1035
제거하고 싶은 컬럼 : ['tmax', 'tmin', 'tavg', 'depart', 'dewpoint', 'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'snowfall', 'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed']
제거한 int 컬럼 : ['tmax', 'tmin', 'tavg', 'dewpoint', 'wetbulb', 'heat', 'cool', 'sunrise', 'sunset']
제거한 float 컬럼 : ['depart', 'snowfall', 'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed']
제거한 후 데이터프레임 length : 990

       VIF Factor     features
0        1.088000     snowfall
1        1.132311    resultdir
2        1.210389  preciptotal
3        4.249524       depart
4        6.999426  resultspeed
5        7.435239     avgspeed
6        8.915346       sunset
7       18.011337      sunrise
8       93.057186  stnpressure
9       97.734978     dewpoint
10     104.820639     sealevel
11     294.326623      wetbulb
12    1363.071175         tmax
13    1374.975684         tmin
14    2146.775510         cool
15    3868.403119         heat
16  158121.142524         tavg

In [22]:
station_4 = cf.getSpecifiedWeatherData(df_weather, 4)
temp = cf.isThereNoneData(station_4)

M Data over 60% : []
T Data over 60% : []
B Data over 60% : []

In [23]:
cf.remove_columns(station_4, ["date", "codesum", "station_nbr"])
station_4_dropped_all = cf.remove_m_row(station_4)
getVif(station_4_dropped_all)

제거한 컬럼명 : ['date', 'codesum', 'station_nbr']
원본 데이터프레임 length : 1035
제거하고 싶은 컬럼 : ['tmax', 'tmin', 'tavg', 'depart', 'dewpoint', 'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'snowfall', 'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed']
제거한 int 컬럼 : ['tmax', 'tmin', 'tavg', 'dewpoint', 'wetbulb', 'heat', 'cool', 'sunrise', 'sunset']
제거한 float 컬럼 : ['depart', 'snowfall', 'preciptotal', 'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed']
제거한 후 데이터프레임 length : 976

       VIF Factor     features
0        1.171410    resultdir
1        1.193681  preciptotal
2        4.322619       depart
3        5.382982       sunset
4        7.362468  resultspeed
5        7.834934     avgspeed
6       10.366321      sunrise
7       66.969553     dewpoint
8       93.054081  stnpressure
9      109.542104     sealevel
10     208.906684      wetbulb
11     786.670907         tmin
12     822.996031         tmax
13    1193.337839         heat
14    4301.726056         cool
15  220187.546601         tavg
16            NaN     snowfall