In [1]:
# Import libraries

import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns


# Pretty display for notebooks

%matplotlib inline


# Allows the use of display() for DataFrames
from IPython.display import display 

# Ignore the warnings
import warnings
warnings.filterwarnings('ignore')

# Load the dataset
train = pd.read_csv("../asset/train.csv")
test = pd.read_csv("../asset/test.csv")
weather = pd.read_csv("../asset/weather.csv")
key = pd.read_csv("../asset/key.csv")
submission_example = pd.read_csv("../asset/sampleSubmission.csv")

# Success - Display the first record
print("Train data : ", train.shape)
print("Test  data : ", test.shape)
print("weather  data : ", weather.shape)
print("key  data : ", key.shape)
print("submission  data : ", submission_example.shape)

import pickle
import awesome_functions as cf
import datetime
from dateutil.parser import parse

# 원본을 유지하기 위해서 카피
df_train = train.copy()
df_weather = weather.copy()
df_key = key.copy()
df_test = test.copy()

Train data :  (4617600, 4)
Test  data :  (526917, 3)
weather  data :  (20517, 20)
key  data :  (45, 2)
submission  data :  (526917, 2)

In [2]:
dt = datetime.datetime.strptime("2014-10-31", "%Y-%m-%d")

In [3]:
parse('2014-10-31')+datetime.timedelta(days=5)

datetime.datetime(2014, 11, 5, 0, 0)

In [5]:
df_weather["year"] = df_weather["date"]

def handle_date_Y(a):
    return parse(a).year

def handle_date_M(a):
    return parse(a).month

def handle_date_D(a):
    return parse(a).day

In [6]:
df_weather['year'] = df_weather['date'].apply(handle_date_Y)

In [7]:
df_weather['month'] = df_weather['date'].apply(handle_date_M)

In [8]:
df_weather['day'] = df_weather['date'].apply(handle_date_D)

In [9]:
df_weather

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed,year,month,day
0,1,2012-01-01,52,31,42,M,36,40,23,0,...,M,0.05,29.78,29.92,3.6,20,4.6,2012,1,1
1,2,2012-01-01,48,33,41,16,37,39,24,0,...,0.0,0.07,28.82,29.91,9.1,23,11.3,2012,1,1
2,3,2012-01-01,55,34,45,9,24,36,20,0,...,0.0,0.00,29.77,30.47,9.9,31,10.0,2012,1,1
3,4,2012-01-01,63,47,55,4,28,43,10,0,...,0.0,0.00,29.79,30.48,8.0,35,8.2,2012,1,1
4,6,2012-01-01,63,34,49,0,31,43,16,0,...,0.0,0.00,29.95,30.47,14.0,36,13.8,2012,1,1
5,7,2012-01-01,50,33,42,M,26,35,23,0,...,0.0,0.00,29.15,30.54,10.3,32,10.2,2012,1,1
6,8,2012-01-01,66,45,M,M,34,46,M,M,...,M,0.00,30.05,M,11.0,36,10.9,2012,1,1
7,9,2012-01-01,34,19,27,M,17,23,38,0,...,M,T,29.34,30.09,22.8,30,22.5,2012,1,1
8,10,2012-01-01,73,53,63,M,55,58,2,0,...,M,0.00,30.16,30.19,5.1,24,5.5,2012,1,1
9,11,2012-01-01,72,48,60,7,54,56,5,0,...,0.0,0.00,30.15,30.18,4.6,23,4.8,2012,1,1
10,12,2012-01-01,72,48,60,M,54,57,5,0,...,0.0,0.00,30.15,30.19,4.4,25,4.8,2012,1,1
11,13,2012-01-01,38,18,28,M,12,21,37,0,...,M,0.00,24.60,30.59,2.5,16,6.1,2012,1,1
12,14,2012-01-01,50,34,42,5,25,35,23,0,...,0.0,0.00,29.13,30.52,11.4,32,11.3,2012,1,1
13,15,2012-01-01,48,26,37,16,35,38,28,0,...,0.0,0.09,29.53,29.89,2.5,17,3.8,2012,1,1
14,16,2012-01-01,50,30,40,M,37,40,25,0,...,M,T,29.80,29.89,4.2,21,6.8,2012,1,1
15,17,2012-01-01,56,38,47,M,23,37,18,0,...,0.0,0.00,29.83,30.50,5.4,32,5.8,2012,1,1
16,18,2012-01-01,59,40,50,4,28,40,15,0,...,0.0,0.00,29.98,30.49,9.0,33,8.9,2012,1,1
17,19,2012-01-01,38,25,32,10,26,30,33,0,...,0.5,0.12,29.06,29.79,14.6,29,15.6,2012,1,1
18,20,2012-01-01,59,41,50,M,28,40,15,0,...,0.0,0.00,29.78,30.48,10.9,33,10.8,2012,1,1
19,1,2012-01-02,50,31,41,M,26,35,24,0,...,M,0.01,29.44,29.62,9.8,24,10.3,2012,1,2
20,2,2012-01-02,46,28,37,12,24,32,28,0,...,T,0.01,28.51,29.62,12.7,26,13.3,2012,1,2
21,3,2012-01-02,45,24,35,-1,11,28,30,0,...,0.0,0.00,29.89,30.63,7.7,32,8.2,2012,1,2
22,4,2012-01-02,60,37,49,-2,26,39,16,0,...,0.0,0.00,29.93,30.64,3.7,36,4.8,2012,1,2
23,6,2012-01-02,60,30,45,-4,27,38,20,0,...,0.0,0.00,30.09,30.63,9.0,01,9.3,2012,1,2
24,7,2012-01-02,44,26,35,M,17,29,30,0,...,0.0,0.00,29.23,30.66,5.7,34,6.9,2012,1,2
25,8,2012-01-02,59,36,M,M,29,40,M,M,...,M,0.00,30.25,M,6.2,36,6.7,2012,1,2
26,9,2012-01-02,21,11,16,M,8,15,49,0,...,M,T,29.67,30.44,14.4,32,14.7,2012,1,2
27,10,2012-01-02,65,45,55,M,33,46,10,0,...,M,0.00,30.11,30.14,10.2,30,11.2,2012,1,2
28,11,2012-01-02,63,40,52,-1,31,44,13,0,...,0.0,0.00,30.10,30.14,10.2,29,11.1,2012,1,2
29,12,2012-01-02,65,47,56,M,33,46,9,0,...,0.0,0.00,30.09,30.14,11.7,30,12.7,2012,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20487,11,2014-10-30,81,59,70,4,63,65,0,5,...,0.0,0.00,29.91,29.94,1.6,36,3.4,2014,10,30
20488,12,2014-10-30,81,61,71,M,63,66,0,6,...,0.0,0.09,29.90,29.94,1.5,01,3.3,2014,10,30
20489,13,2014-10-30,61,32,47,M,26,38,18,0,...,M,0.00,24.51,30.31,4.8,13,6.7,2014,10,30
20490,14,2014-10-30,77,45,61,5,39,50,4,0,...,0.0,0.00,28.76,30.13,4.4,34,10.4,2014,10,30
20491,15,2014-10-30,56,30,43,0,36,39,22,0,...,0.0,T,29.54,29.94,1.7,31,2.7,2014,10,30
20492,16,2014-10-30,57,34,46,M,39,43,19,0,...,M,0.00,29.79,29.91,4.0,30,4.6,2014,10,30
20493,17,2014-10-30,77,43,60,M,41,50,5,0,...,0.0,0.00,29.45,30.14,2.6,32,5.1,2014,10,30
20494,18,2014-10-30,79,56,68,5,51,58,0,3,...,0.0,T,29.60,30.11,2.9,14,5.6,2014,10,30
20495,19,2014-10-30,51,32,42,-4,33,40,23,0,...,0.0,T,29.31,30.08,5.5,27,6.0,2014,10,30
20496,20,2014-10-30,80,52,66,M,50,57,0,1,...,0.0,0.00,29.40,30.11,1.6,14,4.9,2014,10,30
20497,1,2014-10-31,53,40,47,M,36,41,18,0,...,M,0.00,29.87,30.03,5.4,04,5.8,2014,10,31
20498,2,2014-10-31,49,40,45,0,35,40,20,0,...,0.0,0.00,28.90,30.00,6.2,05,7.0,2014,10,31
20499,3,2014-10-31,55,33,44,-12,32,41,21,0,...,0.0,0.00,29.65,30.36,11.1,35,11.5,2014,10,31
20500,4,2014-10-31,76,56,66,-1,47,56,0,1,...,0.0,0.30,29.55,30.23,6.0,01,6.5,2014,10,31
20501,5,2014-10-31,M,M,M,M,37,M,M,M,...,M,M,M,30.01,10.8,05,M,2014,10,31
20502,6,2014-10-31,76,51,64,0,47,55,1,0,...,0.0,0.17,29.72,30.22,11.3,36,11.7,2014,10,31
20503,7,2014-10-31,58,38,48,M,32,41,17,0,...,0.0,0.00,29.00,30.37,11.0,01,11.6,2014,10,31
20504,8,2014-10-31,78,55,67,M,M,M,0,2,...,M,T,29.82,M,M,M,5.1,2014,10,31
20505,9,2014-10-31,39,25,32,M,18,27,33,0,...,M,0.00,29.74,30.52,8.3,36,8.7,2014,10,31
20506,10,2014-10-31,77,63,70,M,51,59,0,5,...,M,0.00,29.82,29.84,6.9,31,7.8,2014,10,31
20507,11,2014-10-31,75,50,63,-2,53,57,2,0,...,0.0,0.00,29.82,29.85,5.3,30,6.1,2014,10,31
20508,12,2014-10-31,75,60,68,M,53,59,0,3,...,0.0,0.00,29.80,29.85,7.0,32,7.5,2014,10,31
20509,13,2014-10-31,58,35,47,M,28,37,18,0,...,M,0.00,24.36,30.18,6.1,17,7.2,2014,10,31
20510,14,2014-10-31,60,38,49,-7,31,42,16,0,...,0.0,0.00,28.98,30.36,11.9,01,12.5,2014,10,31
20511,15,2014-10-31,50,32,41,-2,34,38,24,0,...,0.0,0.00,29.65,30.03,0.3,03,0.6,2014,10,31
20512,16,2014-10-31,53,34,44,M,35,41,21,0,...,M,0.00,29.90,29.99,4.5,03,5.3,2014,10,31
20513,17,2014-10-31,59,34,47,M,32,41,18,0,...,0.0,0.00,29.72,30.39,9.2,01,9.3,2014,10,31
20514,18,2014-10-31,67,49,58,-4,40,50,7,0,...,0.0,0.00,29.78,30.28,10.6,36,11.2,2014,10,31
20515,19,2014-10-31,45,33,39,-6,24,32,26,0,...,0.1,0.02,29.51,30.24,20.4,34,20.9,2014,10,31
20516,20,2014-10-31,68,50,59,M,39,50,6,0,...,0.0,0.00,29.57,30.27,10.5,36,11.2,2014,10,31

# station 5 삭제

In [10]:
df_weather_ex = df_weather[df_weather['station_nbr']!=5]

In [11]:
df_weather_ex.head()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed,year,month,day
0,1,2012-01-01,52,31,42,M,36,40,23,0,...,M,0.05,29.78,29.92,3.6,20,4.6,2012,1,1
1,2,2012-01-01,48,33,41,16,37,39,24,0,...,0.0,0.07,28.82,29.91,9.1,23,11.3,2012,1,1
2,3,2012-01-01,55,34,45,9,24,36,20,0,...,0.0,0.00,29.77,30.47,9.9,31,10.0,2012,1,1
3,4,2012-01-01,63,47,55,4,28,43,10,0,...,0.0,0.00,29.79,30.48,8.0,35,8.2,2012,1,1
4,6,2012-01-01,63,34,49,0,31,43,16,0,...,0.0,0.00,29.95,30.47,14.0,36,13.8,2012,1,1

In [12]:
cf.isThereNoneData(df_weather_ex)

M Data over 60% : []
T Data over 60% : []
B Data over 60% : []

,Column,Row Count,Missing Data,M Data %,Trace Data,T Data %,Bar Data,B Data %
0,station_nbr,19665,0,0.00,0,0.00,0,0.00
1,date,19665,0,0.00,0,0.00,0,0.00
2,tmax,19665,84,0.43,0,0.00,0,0.00
3,tmin,19665,86,0.44,0,0.00,0,0.00
4,tavg,19665,647,3.29,0,0.00,0,0.00
5,depart,19665,10689,54.36,0,0.00,0,0.00
6,dewpoint,19665,220,1.12,0,0.00,0,0.00
7,wetbulb,19665,400,2.03,0,0.00,0,0.00
8,heat,19665,647,3.29,0,0.00,0,0.00
9,cool,19665,647,3.29,0,0.00,0,0.00
10,sunrise,19665,0,0.00,0,0.00,9625,48.94
11,sunset,19665,0,0.00,0,0.00,9625,48.94
12,codesum,19665,0,0.00,0,0.00,0,0.00
13,snowfall,19665,6402,32.56,311,1.58,0,0.00
14,preciptotal,19665,38,0.19,2410,12.26,0,0.00
15,stnpressure,19665,77,0.39,0,0.00,0,0.00
16,sealevel,19665,1277,6.49,0,0.00,0,0.00
17,resultspeed,19665,143,0.73,0,0.00,0,0.00
18,resultdir,19665,143,0.73,0,0.00,0,0.00
19,avgspeed,19665,53,0.27,0,0.00,0,0.00
20,year,19665,0,0.00,0,0.00,0,0.00
21,month,19665,0,0.00,0,0.00,0,0.00
22,day,19665,0,0.00,0,0.00,0,0.00

In [13]:
df_weather_ex['tmax'] = df_weather_ex['tmax'].apply(cf.changeTypeToInt)
df_weather_ex['tmin'] = df_weather_ex['tmin'].apply(cf.changeTypeToInt)

In [14]:
df_weather_ex = df_weather_ex.sort_values(["station_nbr","date"], ascending=[True,True]).reset_index(drop=True)

In [15]:
cf.isThereNoneData(df_weather_ex)

M Data over 60% : []
T Data over 60% : []
B Data over 60% : []

,Column,Row Count,Missing Data,M Data %,Trace Data,T Data %,Bar Data,B Data %
0,station_nbr,19665,0,0.00,0,0.00,0,0.00
1,date,19665,0,0.00,0,0.00,0,0.00
2,tmax,19665,0,0.00,0,0.00,0,0.00
3,tmin,19665,0,0.00,0,0.00,0,0.00
4,tavg,19665,647,3.29,0,0.00,0,0.00
5,depart,19665,10689,54.36,0,0.00,0,0.00
6,dewpoint,19665,220,1.12,0,0.00,0,0.00
7,wetbulb,19665,400,2.03,0,0.00,0,0.00
8,heat,19665,647,3.29,0,0.00,0,0.00
9,cool,19665,647,3.29,0,0.00,0,0.00
10,sunrise,19665,0,0.00,0,0.00,9625,48.94
11,sunset,19665,0,0.00,0,0.00,9625,48.94
12,codesum,19665,0,0.00,0,0.00,0,0.00
13,snowfall,19665,6402,32.56,311,1.58,0,0.00
14,preciptotal,19665,38,0.19,2410,12.26,0,0.00
15,stnpressure,19665,77,0.39,0,0.00,0,0.00
16,sealevel,19665,1277,6.49,0,0.00,0,0.00
17,resultspeed,19665,143,0.73,0,0.00,0,0.00
18,resultdir,19665,143,0.73,0,0.00,0,0.00
19,avgspeed,19665,53,0.27,0,0.00,0,0.00
20,year,19665,0,0.00,0,0.00,0,0.00
21,month,19665,0,0.00,0,0.00,0,0.00
22,day,19665,0,0.00,0,0.00,0,0.00

In [16]:
cf.saveDataFrameToCsv(df_weather_ex, "nan_to_tavg&tmin")

In [17]:
df_weather_ex['tmax'] = df_weather_ex['tmax'].interpolate()

In [18]:
df_weather_ex['tmin'] = df_weather_ex['tmin'].interpolate()

In [19]:
df_weather_ex

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed,year,month,day
0,1,2012-01-01,52.0,31.0,42,M,36,40,23,0,...,M,0.05,29.78,29.92,3.6,20,4.6,2012,1,1
1,1,2012-01-02,50.0,31.0,41,M,26,35,24,0,...,M,0.01,29.44,29.62,9.8,24,10.3,2012,1,2
2,1,2012-01-03,32.0,11.0,22,M,4,18,43,0,...,M,0.00,29.67,29.87,10.8,31,11.6,2012,1,3
3,1,2012-01-04,28.0,9.0,19,M,-1,14,46,0,...,M,0.00,29.86,30.03,6.3,27,8.3,2012,1,4
4,1,2012-01-05,38.0,25.0,32,M,13,25,33,0,...,M,0.00,29.67,29.84,6.9,25,7.8,2012,1,5
5,1,2012-01-06,46.0,25.0,36,M,21,29,29,0,...,M,T,29.68,29.84,0.3,01,2.4,2012,1,6
6,1,2012-01-07,57.0,28.0,43,M,28,36,22,0,...,M,0.00,29.57,29.76,3.0,26,3.6,2012,1,7
7,1,2012-01-08,45.0,27.0,36,M,22,32,29,0,...,M,0.00,29.90,30.11,5.1,30,6.6,2012,1,8
8,1,2012-01-09,39.0,23.0,31,M,12,25,34,0,...,M,0.00,30.06,30.20,2.3,23,4.0,2012,1,9
9,1,2012-01-10,47.0,29.0,38,M,24,32,27,0,...,M,T,29.69,29.86,5.4,25,6.5,2012,1,10
10,1,2012-01-11,39.0,24.0,32,M,21,29,33,0,...,M,0.00,29.91,30.10,3.4,07,4.2,2012,1,11
11,1,2012-01-12,40.0,31.0,36,M,31,34,29,0,...,M,0.69,29.62,29.74,10.7,05,12.3,2012,1,12
12,1,2012-01-13,50.0,30.0,40,M,27,32,25,0,...,M,0.02,29.24,29.41,8.7,24,12.7,2012,1,13
13,1,2012-01-14,35.0,14.0,25,M,12,23,40,0,...,M,0.00,29.58,29.81,11.1,28,12.5,2012,1,14
14,1,2012-01-15,16.0,4.0,10,M,-5,7,55,0,...,M,0.00,30.09,30.31,11.2,31,11.6,2012,1,15
15,1,2012-01-16,32.0,8.0,20,M,3,17,45,0,...,M,0.05,30.29,30.43,5.1,23,7.1,2012,1,16
16,1,2012-01-17,46.0,32.0,39,M,34,37,26,0,...,M,0.09,29.72,29.82,4.9,21,5.9,2012,1,17
17,1,2012-01-18,50.0,19.0,35,M,15,29,30,0,...,M,T,29.55,29.79,13.7,29,15.9,2012,1,18
18,1,2012-01-19,31.0,13.0,22,M,11,20,43,0,...,M,0.02,30.03,30.18,1.4,04,2.9,2012,1,19
19,1,2012-01-20,31.0,19.0,25,M,12,23,40,0,...,M,0.08,29.90,30.11,6.0,29,6.7,2012,1,20
20,1,2012-01-21,20.0,13.0,17,M,9,16,48,0,...,M,0.12,30.08,30.26,5.9,01,6.0,2012,1,21
21,1,2012-01-22,28.0,7.0,18,M,12,18,47,0,...,M,T,30.34,30.54,3.4,04,3.7,2012,1,22
22,1,2012-01-23,48.0,27.0,38,M,30,34,27,0,...,M,0.12,30.15,30.25,0.8,07,2.2,2012,1,23
23,1,2012-01-24,55.0,41.0,48,M,39,44,17,0,...,M,T,29.73,29.92,6.8,25,8.3,2012,1,24
24,1,2012-01-25,42.0,35.0,39,M,23,32,26,0,...,M,0.00,29.97,30.15,8.2,28,8.7,2012,1,25
25,1,2012-01-26,43.0,32.0,38,M,23,31,27,0,...,M,0.15,30.00,30.16,1.7,35,4.2,2012,1,26
26,1,2012-01-27,45.0,34.0,40,M,36,38,25,0,...,M,1.14,29.46,29.57,3.2,36,7.5,2012,1,27
27,1,2012-01-28,48.0,32.0,40,M,27,35,25,0,...,M,0.00,29.68,29.88,5.5,25,8.0,2012,1,28
28,1,2012-01-29,43.0,31.0,37,M,15,30,28,0,...,M,0.00,29.83,30.01,10.4,25,11.4,2012,1,29
29,1,2012-01-30,39.0,25.0,32,M,15,27,33,0,...,M,T,29.91,30.12,6.6,28,7.7,2012,1,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19635,20,2014-10-02,95.0,65.0,80,M,67,71,0,15,...,0.0,0.47,29.15,29.80,4.4,19,9.7,2014,10,2
19636,20,2014-10-03,83.0,58.0,71,M,49,59,0,6,...,0.0,0.00,29.42,30.11,8.2,34,9.0,2014,10,3
19637,20,2014-10-04,80.0,47.0,64,M,36,51,1,0,...,0.0,0.00,29.36,30.09,2.2,15,5.3,2014,10,4
19638,20,2014-10-05,86.0,61.0,74,M,56,63,0,9,...,0.0,0.00,29.15,29.87,7.3,17,8.0,2014,10,5
19639,20,2014-10-06,86.0,65.0,76,M,62,67,0,11,...,0.0,0.16,29.15,29.84,6.7,15,8.5,2014,10,6
19640,20,2014-10-07,97.0,70.0,84,M,65,71,0,19,...,0.0,0.00,29.17,29.86,5.7,17,8.3,2014,10,7
19641,20,2014-10-08,91.0,74.0,83,M,68,72,0,18,...,0.0,0.00,29.26,29.95,8.4,15,9.7,2014,10,8
19642,20,2014-10-09,93.0,76.0,85,M,68,73,0,20,...,0.0,0.00,29.19,29.90,8.8,16,9.4,2014,10,9
19643,20,2014-10-10,94.0,65.0,80,M,65,71,0,15,...,0.0,0.55,29.17,29.86,2.8,20,8.1,2014,10,10
19644,20,2014-10-11,66.0,53.0,60,M,54,57,5,0,...,0.0,0.42,29.33,30.03,9.6,31,10.0,2014,10,11
19645,20,2014-10-12,76.0,51.0,64,M,58,61,1,0,...,0.0,T,29.08,29.83,7.2,15,8.3,2014,10,12
19646,20,2014-10-13,77.0,60.0,69,M,52,57,0,4,...,0.0,1.36,29.10,29.79,13.0,29,15.3,2014,10,13
19647,20,2014-10-14,79.0,55.0,67,M,41,53,0,2,...,0.0,0.00,29.33,30.01,10.7,29,11.6,2014,10,14
19648,20,2014-10-15,85.0,48.0,67,M,44,55,0,2,...,0.0,0.00,29.29,30.01,0.7,19,3.2,2014,10,15
19649,20,2014-10-16,89.0,59.0,74,M,45,58,0,9,...,0.0,0.00,29.15,29.86,5.7,19,6.8,2014,10,16
19650,20,2014-10-17,89.0,60.0,75,M,53,62,0,10,...,0.0,0.00,29.18,29.87,1.8,10,4.6,2014,10,17
19651,20,2014-10-18,84.0,65.0,75,M,55,62,0,10,...,0.0,0.00,29.34,30.03,7.7,06,8.3,2014,10,18
19652,20,2014-10-19,78.0,57.0,68,M,54,59,0,3,...,0.0,0.00,29.36,30.08,6.2,11,6.7,2014,10,19
19653,20,2014-10-20,83.0,57.0,70,M,57,62,0,5,...,0.0,0.00,29.33,30.03,2.8,14,3.5,2014,10,20
19654,20,2014-10-21,83.0,55.0,69,M,56,61,0,4,...,0.0,0.00,29.34,30.04,3.4,14,3.7,2014,10,21
19655,20,2014-10-22,81.0,60.0,71,M,58,63,0,6,...,0.0,0.00,29.38,30.08,5.8,12,6.0,2014,10,22
19656,20,2014-10-23,80.0,63.0,72,M,55,61,0,7,...,0.0,T,29.39,30.09,4.7,14,6.0,2014,10,23
19657,20,2014-10-24,85.0,60.0,73,M,57,63,0,8,...,0.0,0.00,29.39,30.09,4.6,17,5.9,2014,10,24
19658,20,2014-10-25,90.0,64.0,77,M,59,65,0,12,...,0.0,0.00,29.36,30.07,2.5,17,5.0,2014,10,25
19659,20,2014-10-26,89.0,68.0,79,M,56,64,0,14,...,0.0,0.00,29.21,29.92,6.3,17,8.0,2014,10,26
19660,20,2014-10-27,85.0,66.0,76,M,59,65,0,11,...,0.0,0.00,29.11,29.82,10.0,18,10.4,2014,10,27
19661,20,2014-10-28,80.0,68.0,74,M,60,65,0,9,...,0.0,0.00,29.30,29.97,3.1,36,6.4,2014,10,28
19662,20,2014-10-29,78.0,55.0,67,M,47,56,0,2,...,0.0,0.00,29.42,30.12,4.9,06,6.1,2014,10,29
19663,20,2014-10-30,80.0,52.0,66,M,50,57,0,1,...,0.0,0.00,29.40,30.11,1.6,14,4.9,2014,10,30
19664,20,2014-10-31,68.0,50.0,59,M,39,50,6,0,...,0.0,0.00,29.57,30.27,10.5,36,11.2,2014,10,31

In [20]:
cf.isThereNoneData(df_weather_ex)

M Data over 60% : []
T Data over 60% : []
B Data over 60% : []

,Column,Row Count,Missing Data,M Data %,Trace Data,T Data %,Bar Data,B Data %
0,station_nbr,19665,0,0.00,0,0.00,0,0.00
1,date,19665,0,0.00,0,0.00,0,0.00
2,tmax,19665,0,0.00,0,0.00,0,0.00
3,tmin,19665,0,0.00,0,0.00,0,0.00
4,tavg,19665,647,3.29,0,0.00,0,0.00
5,depart,19665,10689,54.36,0,0.00,0,0.00
6,dewpoint,19665,220,1.12,0,0.00,0,0.00
7,wetbulb,19665,400,2.03,0,0.00,0,0.00
8,heat,19665,647,3.29,0,0.00,0,0.00
9,cool,19665,647,3.29,0,0.00,0,0.00
10,sunrise,19665,0,0.00,0,0.00,9625,48.94
11,sunset,19665,0,0.00,0,0.00,9625,48.94
12,codesum,19665,0,0.00,0,0.00,0,0.00
13,snowfall,19665,6402,32.56,311,1.58,0,0.00
14,preciptotal,19665,38,0.19,2410,12.26,0,0.00
15,stnpressure,19665,77,0.39,0,0.00,0,0.00
16,sealevel,19665,1277,6.49,0,0.00,0,0.00
17,resultspeed,19665,143,0.73,0,0.00,0,0.00
18,resultdir,19665,143,0.73,0,0.00,0,0.00
19,avgspeed,19665,53,0.27,0,0.00,0,0.00
20,year,19665,0,0.00,0,0.00,0,0.00
21,month,19665,0,0.00,0,0.00,0,0.00
22,day,19665,0,0.00,0,0.00,0,0.00

In [21]:
cf.saveDataFrameToCsv(df_weather_ex, "handling_tmin&tmax")

In [22]:
df_weather_ex['tmax'] = df_weather_ex['tmax'].apply(cf.changeTypeToInt)
df_weather_ex['tmin'] = df_weather_ex['tmin'].apply(cf.changeTypeToInt)

In [23]:
cf.isThereNoneData(df_weather_ex)

M Data over 60% : []
T Data over 60% : []
B Data over 60% : []

,Column,Row Count,Missing Data,M Data %,Trace Data,T Data %,Bar Data,B Data %
0,station_nbr,19665,0,0.00,0,0.00,0,0.00
1,date,19665,0,0.00,0,0.00,0,0.00
2,tmax,19665,0,0.00,0,0.00,0,0.00
3,tmin,19665,0,0.00,0,0.00,0,0.00
4,tavg,19665,647,3.29,0,0.00,0,0.00
5,depart,19665,10689,54.36,0,0.00,0,0.00
6,dewpoint,19665,220,1.12,0,0.00,0,0.00
7,wetbulb,19665,400,2.03,0,0.00,0,0.00
8,heat,19665,647,3.29,0,0.00,0,0.00
9,cool,19665,647,3.29,0,0.00,0,0.00
10,sunrise,19665,0,0.00,0,0.00,9625,48.94
11,sunset,19665,0,0.00,0,0.00,9625,48.94
12,codesum,19665,0,0.00,0,0.00,0,0.00
13,snowfall,19665,6402,32.56,311,1.58,0,0.00
14,preciptotal,19665,38,0.19,2410,12.26,0,0.00
15,stnpressure,19665,77,0.39,0,0.00,0,0.00
16,sealevel,19665,1277,6.49,0,0.00,0,0.00
17,resultspeed,19665,143,0.73,0,0.00,0,0.00
18,resultdir,19665,143,0.73,0,0.00,0,0.00
19,avgspeed,19665,53,0.27,0,0.00,0,0.00
20,year,19665,0,0.00,0,0.00,0,0.00
21,month,19665,0,0.00,0,0.00,0,0.00
22,day,19665,0,0.00,0,0.00,0,0.00

In [24]:
cf.saveDataFrameToCsv(df_weather_ex, "tmin&tmax_to_int")

# Handling tavg

In [25]:
df_weather_ex['tavg'] = (df_weather_ex['tmax']+df_weather_ex['tmin'])/2
df_weather_ex['tavg'] = df_weather_ex['tavg'].apply(cf.changeTypeToInt)

In [26]:
cf.isThereNoneData(df_weather_ex)

M Data over 60% : []
T Data over 60% : []
B Data over 60% : []

,Column,Row Count,Missing Data,M Data %,Trace Data,T Data %,Bar Data,B Data %
0,station_nbr,19665,0,0.00,0,0.00,0,0.00
1,date,19665,0,0.00,0,0.00,0,0.00
2,tmax,19665,0,0.00,0,0.00,0,0.00
3,tmin,19665,0,0.00,0,0.00,0,0.00
4,tavg,19665,0,0.00,0,0.00,0,0.00
5,depart,19665,10689,54.36,0,0.00,0,0.00
6,dewpoint,19665,220,1.12,0,0.00,0,0.00
7,wetbulb,19665,400,2.03,0,0.00,0,0.00
8,heat,19665,647,3.29,0,0.00,0,0.00
9,cool,19665,647,3.29,0,0.00,0,0.00
10,sunrise,19665,0,0.00,0,0.00,9625,48.94
11,sunset,19665,0,0.00,0,0.00,9625,48.94
12,codesum,19665,0,0.00,0,0.00,0,0.00
13,snowfall,19665,6402,32.56,311,1.58,0,0.00
14,preciptotal,19665,38,0.19,2410,12.26,0,0.00
15,stnpressure,19665,77,0.39,0,0.00,0,0.00
16,sealevel,19665,1277,6.49,0,0.00,0,0.00
17,resultspeed,19665,143,0.73,0,0.00,0,0.00
18,resultdir,19665,143,0.73,0,0.00,0,0.00
19,avgspeed,19665,53,0.27,0,0.00,0,0.00
20,year,19665,0,0.00,0,0.00,0,0.00
21,month,19665,0,0.00,0,0.00,0,0.00
22,day,19665,0,0.00,0,0.00,0,0.00

In [27]:
df_weather_ex.head()

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed,year,month,day
0,1,2012-01-01,52,31,41,M,36,40,23,0,...,M,0.05,29.78,29.92,3.6,20,4.6,2012,1,1
1,1,2012-01-02,50,31,40,M,26,35,24,0,...,M,0.01,29.44,29.62,9.8,24,10.3,2012,1,2
2,1,2012-01-03,32,11,21,M,4,18,43,0,...,M,0.00,29.67,29.87,10.8,31,11.6,2012,1,3
3,1,2012-01-04,28,9,18,M,-1,14,46,0,...,M,0.00,29.86,30.03,6.3,27,8.3,2012,1,4
4,1,2012-01-05,38,25,31,M,13,25,33,0,...,M,0.00,29.67,29.84,6.9,25,7.8,2012,1,5

In [28]:
cf.saveDataFrameToCsv(df_weather_ex, "handle_tavg")

# heat&cold값 처리

## heat값 처리

In [29]:
df_weather_ex['heat'] = df_weather_ex['heat'].apply(cf.changeTypeToInt)

In [30]:
df_weather_ex['tavg'] = df_weather_ex['tavg'].apply(cf.changeTypeToInt)

In [31]:
# nan 값 찾아서 갯수 세기
pd.isnull(df_weather_ex['heat']).sum()

647

In [42]:
df_weather_ex['heat'] = 65-df_weather_ex['tavg']

In [43]:
pd.isnull(df_weather_ex['heat']).sum()

0

In [44]:
df_weather_ex['heat'] = np.where(df_weather_ex['heat'] < 0, 0,df_weather_ex['heat'])

In [45]:
cf.saveDataFrameToCsv(df_weather_ex,'handle_heat')

## cool값 처리

In [46]:
df_weather_ex['cool'] = df_weather_ex['cool'].apply(cf.changeTypeToInt)

In [47]:
pd.isnull(df_weather_ex['cool']).sum()

0

In [48]:
df_weather_ex['cool'] = df_weather_ex['tavg']-65

In [49]:
df_weather_ex['cool'] = np.where(df_weather_ex['cool'] < 0, 0,df_weather_ex['cool'])

In [50]:
pd.isnull(df_weather_ex['cool']).sum()

0

In [51]:
cf.saveDataFrameToCsv(df_weather_ex,'handle_cool')